apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1  # Number of Nginx pods to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: shital1999/nginx:1.1.0
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Nginx Docker image
        ports:
        - containerPort: 80  # Expose container port 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80  # Service port to expose externally
    targetPort: 80  # Target container port
  type: NodePort  # Service type for external access
