---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docker-demo
  namespace: flux-system
spec:
  interval: 10s
  path: ./image-wala
  prune: true
  sourceRef:
    kind: GitRepository
    name: docker-demo
  targetNamespace: docker-wala-namespace
