---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: docker-demo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: docker-demo
  secretRef:
    name: image-automation
  url: ssh://git@github.com/snyaupaneHP/dd-repo.git
