---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: docker-demo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: docker-demo
  url: https://github.com/snyaupaneHP/dd-repo.git
