---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: image-repo
  policy:
    semver:
      range: 1.1.x
