---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: webserver
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/snyaupaneHP/FluxCD
